name: "nyc_elt"
version: "1.0.0"
profile: "default"

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]      
macro-paths: ["macros"]       
snapshot-paths: ["snapshots"]  

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  nyc_elt:
    +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: view
