default:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('PGHOST') }}"
      user: "{{ env_var('PGUSER') }}"
      password: "{{ env_var('PGPASSWORD') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      port: "{{ env_var('PGPORT','5432') | int }}"
      schema: "public"
      threads: 4
      sslmode: "require"
